# Generated by Django 5.1.4 on 2025-02-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image_url', models.ImageField(default='images/default.png', upload_to='images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('support_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='نام انتشارات')),
                ('ia_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'انتشارات',
                'verbose_name_plural': 'انتشارات',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان تگ')),
                ('description', models.CharField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=100, null=True, verbose_name='عنوان در url')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'سته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, default='کتابخانه', max_length=100, null=True, verbose_name='فروشنده')),
                ('author', models.CharField(default=None, max_length=100, verbose_name='نویسنده')),
                ('print', models.CharField(default=None, max_length=100, verbose_name='نوبت چاپ')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('pages', models.IntegerField(default=0, verbose_name='تعداد صفحات')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Farsi'), ('ar', 'Arabic')], default='fa', max_length=100, verbose_name='زبان')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.productpublisher', verbose_name='انتشارات')),
            ],
            options={
                'verbose_name': 'اطلاعات محصول',
                'verbose_name_plural': 'اطلاعات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('price', models.IntegerField(db_index=True, default=0, help_text='تومان', verbose_name='قیمت')),
                ('discounted_price', models.IntegerField(blank=True, db_index=True, default=0, help_text='تومان', null=True, verbose_name='قیمت پس از تخفیف')),
                ('content', models.TextField(null=True, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در url')),
                ('sell_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین تغییرات')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(blank=True, to='home.categories', verbose_name='دسته بندی')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.image', verbose_name='تصویر')),
                ('Info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Information', to='home.productsinfo', verbose_name='اطلاعات تکمیلی')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='home.producttag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['order'],
            },
        ),
    ]
