# Generated by Django 5.1.4 on 2025-02-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=100, null=True, verbose_name='عنوان در url')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'سته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('support_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='نام انتشارات')),
                ('ia_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'انتشارات',
                'verbose_name_plural': 'انتشارات',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان تگ')),
                ('description', models.CharField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, default='کتابخانه', max_length=100, null=True, verbose_name='فروشنده')),
                ('writer', models.CharField(default=None, max_length=100, verbose_name='نویسنده')),
                ('print', models.CharField(default=None, max_length=100, verbose_name='نوبت چاپ')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('pages', models.IntegerField(default=0, verbose_name='تعداد صفحات')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Farsi'), ('ar', 'Arabic')], default='fa', max_length=100, verbose_name='زبان')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.productpublisher', verbose_name='انتشارات')),
            ],
            options={
                'verbose_name': 'اطلاعات محصول',
                'verbose_name_plural': 'اطلاعات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('price', models.IntegerField(db_index=True, default=0, help_text='تومان', verbose_name='قیمت')),
                ('price_after_discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='قیمت بعد از تخفیف')),
                ('content', models.TextField(null=True, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در url')),
                ('sell_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین تغییرات')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='images/', verbose_name='تصویر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(blank=True, to='home.categories', verbose_name='دسته بندی')),
                ('Info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Information', to='home.productsinfo', verbose_name='اطلاعات تکمیلی')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='home.producttag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
