# Generated by Django 5.2b1 on 2025-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
