# Generated by Django 5.1.4 on 2025-02-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='price_after_discount',
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='تومان', null=True, verbose_name='قیمت پس از تخفیف'),
        ),
        migrations.AddField(
            model_name='categories',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.discount', verbose_name='تخفیف'),
        ),
    ]
