# Generated by Django 5.1.4 on 2025-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='test',
            field=models.CharField(blank=True, null=True),
        ),
    ]
