# Generated by Django 5.1.4 on 2025-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_users_username_users_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
