# Generated by Django 5.1.4 on 2025-01-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('ia_active', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='test',
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.productpublisher', verbose_name='انتشارات'),
        ),
    ]
