# Generated by Django 5.1.4 on 2025-02-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_discount_remove_products_price_after_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinfo',
            old_name='writer',
            new_name='author',
        ),
    ]
