# Generated by Django 5.1.4 on 2025-02-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='Slider',
        ),
    ]
