# Generated by Django 5.1.4 on 2024-12-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_image_blog_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('support_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('content', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('seller_name', models.CharField(max_length=100)),
                ('sell_count', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
