# Generated by Django 5.1.4 on 2024-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_info_products_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='print',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='publisher',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='writer',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller_name',
            field=models.CharField(blank=True, default='کتابخانه', max_length=100, null=True),
        ),
    ]
