# Generated by Django 5.1.4 on 2024-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_products_pages_products_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Farsi'), ('ar', 'Arabic')], default='fa', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ریال', max_digits=15),
        ),
    ]
