# Generated by Django 5.1.4 on 2024-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_products_language_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=100)),
                ('payment_info', models.JSONField(blank=True, default=list, editable=False, help_text='Store detailed payment information as JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
